### ISSUE TITLE
Out of memory after running through a few evaluation samples on VIPSeg VSS

### ISSUE THREAD

**Issue by SHMCU** [lxtGH/Tube-Link#10]
When running test_video.py on VIPSeg VSS using the release VIPSeg SwinL model, the maskformer_fusion_head.py reports error saying query_index not on the same device as the data, I found it was on cpu not on gpu, so I changed this line to "query_index = torch.arange(len(mask_cls), device='cuda')", then it can run. Is this a bug?

Another issue is out of memory:
I can run the model swinl on VIPSeg VSS with clip length 6. However, the test_video.py reports out of memory after 35 samples. It seems the memory consumption is always increasing. I changed the clip length to 2, it can run through 99 clips then out of memory.
V100 GPU is used.
Could you give some suggestions on this?

**Comment by lxtGH** [comment]
For Swin Large, we use A100 with 80G memory for training and testing. If you do not have such GPUs, you can short the input size of the video.

**Comment by SHMCU** [comment]
> For Swin Large, we use A100 with 80G memory for training and testing. If you do not have such GPUs, you can short the input size of the video.

Shorten the input size of the video? Do you mean smaller clip size or smaller length of the whole input video?
